# This file contains a mix of the autogenerated hardware-configuration.nix and
#  other hardware or low-level related options.
{
  this,
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sr_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    loader = {
      efi = {
        canTouchEfiVariables = true;
      };
      systemd-boot.enable = false;
      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        useOSProber = true;
      };
    };
  };
  environment.systemPackages = with pkgs; [
    grub2 # Makes grub commands available in the terminal.
  ];

  # https://www.marcusfolkesson.se/blog/determine-wakeup-cause-with-acpi/
  # https://askubuntu.com/a/1469469
  # This makes it so that I can suspend the system without it waking up immediately.
  # Also tried solutions from https://wiki.archlinux.org/title/Power_management/Wakeup_triggers but but they didn't work.
  systemd.tmpfiles.rules = [
    "w /proc/acpi/wakeup - - - - XH00"
  ];

  time.timeZone = "Europe/Lisbon";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_IE.UTF-8";
    LC_IDENTIFICATION = "en_IE.UTF-8";
    LC_MEASUREMENT = "en_IE.UTF-8";
    LC_MONETARY = "en_IE.UTF-8";
    LC_NAME = "en_IE.UTF-8";
    LC_NUMERIC = "en_IE.UTF-8";
    LC_PAPER = "en_IE.UTF-8";
    LC_TELEPHONE = "en_IE.UTF-8";
    LC_TIME = "en_IE.UTF-8";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  networking.networkmanager.enable = true;
  # This makes the system wait for the network before booting. This also fails rebuild if enabled.
  systemd.services.NetworkManager-wait-online.enable = lib.mkForce false;

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  services.autorandr.enable = true;

  # Configure keyboard layout.
  # Run the following to find out available options:
  #  cat $(nix-build --no-out-link '<nixpkgs>' -A xkeyboard_config)/etc/X11/xkb/rules/base.lst
  services.xserver = {
    xkb = {
      layout = "us,us";
      variant = ",intl";
    };
  };

  hardware.xpadneo.enable = true;
  hardware.bluetooth = {
    enable = true;
    # Had to remove ~/.config/bluedevilglobalrc for bluetooth to be online on startup.
    # https://www.reddit.com/r/ManjaroLinux/comments/12fgj3o/kde_plasma_bluetooth_not_automatically_powered_on/
    powerOnBoot = true;
    settings = {
      General = {
        ControllerMode = "dual";
        FastConnectable = "true";
        # Experimental = "true";
        # Had to add these settings for the Xbox controllers to connect.
        # https://github.com/bluez/bluez/issues/155#issuecomment-2646656304
        # If that still doesn't work try:
        # https://github.com/bluez/bluez/issues/155#issuecomment-897362404
        # https://github.com/bluez/bluez/issues/155#issuecomment-1006563750
        Privacy = "device";
        JustWorksRepairing = "always";
        Class = "0x000100";
      };
      Policy = {
        AutoEnable = "true";
      };
    };
  };

  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
  # services.pulseaudio = {
  #   enable = true;
  #   support32Bit = true;
  # };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/4ad2648f-df23-4750-b957-3436f592f847";
      fsType = "btrfs";
      options = ["compress=zstd"];
    };
    "/home" = {
      device = "/dev/disk/by-uuid/4ad2648f-df23-4750-b957-3436f592f847";
      fsType = "btrfs";
      options = ["subvol=home" "compress=zstd"];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/4ad2648f-df23-4750-b957-3436f592f847";
      fsType = "btrfs";
      options = ["subvol=nix" "compress=zstd" "noatime"];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };
    "/swap" = {
      device = "/dev/disk/by-uuid/4ad2648f-df23-4750-b957-3436f592f847";
      fsType = "btrfs";
      options = ["subvol=swap" "noatime"];
    };
  };
  swapDevices = [{device = "/swap/swapfile";}];
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = ["/"];
  };
  services.snapper.configs = {
    # root is the default config name
    # This required "sudo btrfs subvolume create /home/.snapshots" to be run once
    root = {
      SUBVOLUME = "/home";
      ALLOW_USERS = ["${this.username}"];
      TIMELINE_CREATE = true;
      TIMELINE_CLEANUP = true;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault this.hostPlatform;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
